services:
    app:
        build:
            context: .
            args:
                uid: ${UID}
                username: ${USERNAME}
        restart: unless-stopped
        ports:
            - 8080:80
            - 5173:5173
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        volumes:
            - ./app:/var/www/html
            - .:/home/${USERNAME}/project
    mysql:
        image: mysql:8.0
        restart: unless-stopped
        ports:
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - ./dump:/docker-entrypoint-initdb.d:ro
            - ./conf:/etc/mysql/conf.d:ro
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin
        restart: unless-stopped
        ports:
            - 8081:80
        environment:
            - PMA_HOST=mysql
volumes:
    persistent:
